float64[7] tau_d
float64[7] tau_J
float64[7] tau_J_d
#
float64[7] q
float64[7] q_observe
float64[7] dq
float64[7] S3
float64[7] dq_filter
float64[7] dq_observe

# float64[7] ddq
float64[7] q_d
float64[7] dq_d
float64[7] ddq_d
float64[7] qError
float64[7] dqError

float64[6] X
float64[6] dX
# float64[6] ddX
float64[6] X_d
float64[6] dX_d
float64[6] ddX_d
float64[6] Xerror
float64[6] dXerror

float64[6] S
float64[7] tau_ext
float64[7] tau_msr
float64[7] dtau_msr
float64[6] F_msr
float64[6] F_ext0
float64[6] F_extK

#新阻抗
float64[7] tmp1
float64[6] tmp2